# Generated by Django 6.0 on 2025-12-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="Введите Ваше имя",
                max_length=150,
                null=True,
                verbose_name="Имя",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="Введите фамилию",
                max_length=150,
                null=True,
                verbose_name="Фамилия",
            ),
        ),
    ]
