# Generated by Django 6.0 on 2025-12-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Является ли пользователь сотрудником?",
                verbose_name="Сотрудник",
            ),
        ),
    ]
