# Generated by Django 6.0 on 2025-12-27 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Укажите номер столика",
                        unique=True,
                        verbose_name="Номер столика",
                    ),
                ),
                (
                    "max_guests",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Укажите максимальную вместимость гостей за столиком",
                        verbose_name="Максимальная вместимость столика",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Введите описание",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Добавьте фото столика",
                        null=True,
                        upload_to="booking_tables/media",
                        verbose_name="Фото столика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Столик",
                "verbose_name_plural": "Столики",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_of_guests",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Укажите количество гостей",
                        verbose_name="Количество гостей",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Укажите дату посещения",
                        verbose_name="Дата посещения",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Укажите время посещения",
                        verbose_name="Время посещения",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Введите комментарий",
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        help_text="Выберите гостя",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Гость",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        help_text="Выберите столик",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="booking_tables.table",
                        verbose_name="Столик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Брони",
                "ordering": [
                    "guest",
                    "number_of_guests",
                    "date",
                    "time",
                    "comment",
                    "table",
                ],
            },
        ),
    ]
