# Generated by Django 6.0 on 2025-12-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_tables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="is_publish",
            field=models.BooleanField(
                default=True, verbose_name="Доступен к бронированию"
            ),
        ),
    ]
