# Generated by Django 6.0 on 2026-01-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_tables", "0002_table_is_publish"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_title",
                    models.TextField(
                        blank=True,
                        help_text="Укажите должность",
                        null=True,
                        verbose_name="Должность",
                    ),
                ),
                (
                    "full_name",
                    models.TextField(
                        blank=True,
                        help_text="Укажите ФИО",
                        null=True,
                        verbose_name="ФИО",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Добавьте фото сотрудника",
                        null=True,
                        upload_to="booking_tables/media",
                        verbose_name="Фото сотрудника",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "ordering": ["job_title", "full_name"],
            },
        ),
        migrations.AlterField(
            model_name="booking",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Введите комментарии (пожелания)",
                null=True,
                verbose_name="Комментарий",
            ),
        ),
    ]
